all:
  hosts:
    zos_host:
      ansible_host: <ZOS_IP_ADDRESS>
      ansible_port: 22
      ansible_user: <ZOS_USERNAME>
      ansible_connection: ssh
      ansible_shell_type: sh
      ansible_python_interpreter: "{{ zos_python_installation_path }}/bin/python3"